# Generated by Django 2.2.2 on 2019-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(choices=[('none', 'NONE'), ('bag', 'BAG'), ('shoes', 'SHOES'), ('watches', 'WATCHES')], default='none', max_length=20),
        ),
    ]
