# Generated by Django 2.2.2 on 2019-06-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('none', 'NONE'), ('bag', 'BAG'), ('shoes', 'SHOES'), ('watches', 'WATCHES')], default='none', max_length=20),
        ),
    ]
