# Generated by Django 2.2.2 on 2019-07-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190703_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='myapp.Product'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
