# Generated by Django 2.2.2 on 2019-07-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190705_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Item in Cart', 'verbose_name_plural': 'Items In Cart'},
        ),
    ]
