# Generated by Django 2.2.2 on 2019-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190705_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('blue', 'Black'), ('white', 'White'), ('grey', 'Grey')], default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('small', 'Size S'), ('medium', 'Size M'), ('large', 'Size L'), ('extra-large', 'Size XL')], default='small', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
