# Generated by Django 2.2.2 on 2019-07-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190705_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(choices=[('', '-- choose a option --'), ('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('', '-- choose a option --'), ('Size S', 'Size S'), ('Size M', 'Size M'), ('Size L', 'Size L'), ('Size XL', 'Size XL')], max_length=20),
        ),
    ]
